# Generated by Django 5.0.6 on 2024-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0003_memomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memomodel',
            name='memo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wordsmodel',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
