# Generated by Django 5.0.6 on 2024-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0005_mcmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsmodel',
            name='fusen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordsmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
