# Generated by Django 5.0.6 on 2024-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0006_wordsmodel_fusen_wordsmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsmodel',
            name='img',
            field=models.ImageField(blank=True, default='images/default.webp', null=True, upload_to='images/'),
        ),
    ]
