# Generated by Django 5.0.6 on 2024-11-24 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0008_alter_memomodel_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcmodel',
            name='reg_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wordsmodel',
            name='reg_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
